CREATE TABLE AREAS (
    idArea INT AUTO_INCREMENT PRIMARY KEY,
    areaDetalle VARCHAR(100) NULL,
    estado TINYINT NULL
);

CREATE TABLE CARRERAS (
    idCarrera INT AUTO_INCREMENT PRIMARY KEY,
    nombreCarrera VARCHAR(100) NULL,
    estado TINYINT NULL
);

CREATE TABLE AREAS_CARRERAS (
    idCarrera INT NOT NULL,
    idArea INT NOT NULL,
    PRIMARY KEY (idCarrera, idArea)
);

CREATE TABLE CAJA (
    idCaja INT AUTO_INCREMENT,
    montoAnterior FLOAT NULL,
    montoIngresado FLOAT NULL,
    total FLOAT NULL,
    fechaCaja DATETIME NOT NULL,
    estado TINYINT NULL,
    PRIMARY KEY (idCaja, fechaCaja)
);

CREATE TABLE CATEGORIAS (
    idCategoria INT AUTO_INCREMENT PRIMARY KEY,
    categoriaDetalle VARCHAR(100) NULL
);

CREATE TABLE CONCEPTOS (
    idConcepto INT AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(100) NULL,
    tipoConcepto VARCHAR(50) NULL
);

CREATE TABLE CONFIGURACION (
    idConfiguracion INT AUTO_INCREMENT PRIMARY KEY,
    maxSedes INT NULL,
    maxUsuarios INT NULL,
    urlLogo TEXT NULL,
    estado TINYINT NULL,
    razonSocial TEXT NULL,
    direccion TEXT NULL,
    telefono CHAR(9) NULL,
    correo VARCHAR(100) NULL,
    ruc CHAR(11) NULL
);

CREATE TABLE PERSONAS (
    idPersona INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NULL,
    apellido VARCHAR(100) NULL,
    dni CHAR(8) NULL,
    telefono CHAR(9) NULL,
    correo VARCHAR(100) NULL,
    idApoderado INT NULL,
    tipoPersona VARCHAR(30) NOT NULL
);

CREATE TABLE CURSOS (
    idCurso INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NULL,
    idPersona INT NULL
);

CREATE TABLE CURSOS_CATEGORIAS (
    idCurso INT NOT NULL,
    idCategoria INT NOT NULL,
    PRIMARY KEY (idCurso, idCategoria)
);

CREATE TABLE DEUDAS (
    idDeuda INT PRIMARY KEY,
    descripcion TEXT NULL,
    idMatricula INT NULL,
    monto FLOAT NULL,
    idConcepto INT NULL,
    estado TINYINT NULL,
    idAlumno CHAR(18) NULL
);

CREATE TABLE PERIODOS (
    idPeriodo INT AUTO_INCREMENT PRIMARY KEY,
    periodoDetalle VARCHAR(100) NULL,
    fechaInicio DATETIME NULL,
    fechaFinal DATETIME NULL
);

CREATE TABLE SEDES (
    idSede INT AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(100) NULL,
    direccion TEXT NULL,
    telefono CHAR(9) NULL,
    estado TINYINT NULL,
    correo VARCHAR(100) NULL
);

CREATE TABLE MATRICULAS (
    idMatricula INT AUTO_INCREMENT PRIMARY KEY,
    idPeriodo INT NULL,
    idCategoria INT NULL,
    idCarrera INT NULL,
    idArea INT NULL,
    monto FLOAT NULL,
    formaPago VARCHAR(50) NULL,
    idSede INT NULL,
    estado VARCHAR(20) NULL,
    idAlumno INT NOT NULL,
    idEmpleado INT NOT NULL
);

CREATE TABLE ASISTENCIAS (
    idAsistencia INT AUTO_INCREMENT PRIMARY KEY,
    fecha DATETIME NULL,
    idMatricula INT NULL,
    estado TINYINT NULL,
    turno CHAR(1) NULL
);

CREATE TABLE USUARIOS (
    idUsuario INT AUTO_INCREMENT PRIMARY KEY,
    password TEXT NULL,
    fotoURL TEXT NULL,
    estado TINYINT NULL,
    usuario VARCHAR(100) NULL,
    idPersona INT NULL
);

CREATE TABLE MOVIMIENTOS (
    idMovimientos INT AUTO_INCREMENT PRIMARY KEY,
    ingreso FLOAT NULL,
    salida FLOAT NULL,
    idUsuario INT NULL,
    idConcepto INT NULL,
    concepto VARCHAR(100) NULL,
    fecha DATETIME NULL,
    estado TINYINT NULL,
    idPago INT NULL,
    observacion TEXT NULL
);

CREATE TABLE NOTAS (
    idNota INT AUTO_INCREMENT PRIMARY KEY,
    idCurso INT NULL,
    notaCurso FLOAT NULL,
    idMatricula INT NULL
);

CREATE TABLE PAGOS (
    idPago INT AUTO_INCREMENT PRIMARY KEY,
    descripcion TEXT NULL,
    montoTotal FLOAT NULL,
    docRel VARCHAR(100) NULL,
    estado TINYINT NULL,
    fecha DATETIME NULL
);

CREATE TABLE PAGOS_DETALLE (
    idPagoDetalle INT AUTO_INCREMENT,
    idPago INT NOT NULL,
    montoPago FLOAT NULL,
    idDeuda INT NULL,
    PRIMARY KEY (idPagoDetalle, idPago)
);

CREATE TABLE ROLES (
    idRol INT AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(100) NULL,
    estado TINYINT NULL
);

CREATE TABLE SIMULACROS (
    idSimulacro INT AUTO_INCREMENT PRIMARY KEY,
    puntaje FLOAT NULL,
    idMatricula INT NULL,
    fecha DATETIME NULL,
    esPagado TINYINT NULL,
    estado TINYINT NULL
);

CREATE TABLE USUARIOS_ROLES (
    idRol INT NOT NULL,
    idUsuario INT NOT NULL,
    PRIMARY KEY (idRol, idUsuario)
);

ALTER TABLE AREAS_CARRERAS
    ADD CONSTRAINT FK_AREAS_CARRERAS_CARRERA FOREIGN KEY (idCarrera) REFERENCES CARRERAS(idCarrera) ON DELETE RESTRICT ON UPDATE RESTRICT,
    ADD CONSTRAINT FK_AREAS_CARRERAS_AREA FOREIGN KEY (idArea) REFERENCES AREAS(idArea) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CURSOS
    ADD CONSTRAINT FK_CURSOS_PERSONA FOREIGN KEY (idPersona) REFERENCES PERSONAS(idPersona) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CURSOS_CATEGORIAS
    ADD CONSTRAINT FK_CURSOS_CATEGORIAS_CURSO FOREIGN KEY (idCurso) REFERENCES CURSOS(idCurso) ON DELETE RESTRICT ON UPDATE RESTRICT,
    ADD CONSTRAINT FK_CURSOS_CATEGORIAS_CATEGORIA FOREIGN KEY (idCategoria) REFERENCES CATEGORIAS(idCategoria) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DEUDAS
    ADD CONSTRAINT FK_DEUDAS_MATRICULA FOREIGN KEY (idMatricula) REFERENCES MATRICULAS(idMatricula) ON DELETE RESTRICT ON UPDATE RESTRICT,
    ADD CONSTRAINT FK_DEUDAS_CONCEPTO FOREIGN KEY (idConcepto) REFERENCES CONCEPTOS(idConcepto) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MATRICULAS
    ADD CONSTRAINT FK_MATRICULAS_PERIODO FOREIGN KEY (idPeriodo) REFERENCES PERIODOS(idPeriodo) ON DELETE RESTRICT ON UPDATE RESTRICT,
    ADD CONSTRAINT FK_MATRICULAS_CATEGORIA FOREIGN KEY (idCategoria) REFERENCES CATEGORIAS(idCategoria) ON DELETE RESTRICT ON UPDATE RESTRICT,
    ADD CONSTRAINT FK_MATRICULAS_AREA_CARRERA FOREIGN KEY (idCarrera, idArea) REFERENCES AREAS_CARRERAS(idCarrera, idArea) ON DELETE RESTRICT ON UPDATE RESTRICT,
    ADD CONSTRAINT FK_MATRICULAS_SEDE FOREIGN KEY (idSede) REFERENCES SEDES(idSede) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ASISTENCIAS
    ADD CONSTRAINT FK_ASISTENCIAS_MATRICULA FOREIGN KEY (idMatricula) REFERENCES MATRICULAS(idMatricula) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE USUARIOS
    ADD CONSTRAINT FK_USUARIOS_PERSONA FOREIGN KEY (idPersona) REFERENCES PERSONAS(idPersona) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MOVIMIENTOS
    ADD CONSTRAINT FK_MOVIMIENTOS_USUARIO FOREIGN KEY (idUsuario) REFERENCES USUARIOS(idUsuario) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE NOTAS
    ADD CONSTRAINT FK_NOTAS_CURSO FOREIGN KEY (idCurso) REFERENCES CURSOS(idCurso) ON DELETE RESTRICT ON UPDATE RESTRICT,
    ADD CONSTRAINT FK_NOTAS_MATRICULA FOREIGN KEY (idMatricula) REFERENCES MATRICULAS(idMatricula) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PAGOS_DETALLE
    ADD CONSTRAINT FK_PAGOS_DETALLE_PAGO FOREIGN KEY (idPago) REFERENCES PAGOS(idPago) ON DELETE RESTRICT ON UPDATE RESTRICT,
    ADD CONSTRAINT FK_PAGOS_DETALLE_DEUDA FOREIGN KEY (idDeuda) REFERENCES DEUDAS(idDeuda) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SIMULACROS
    ADD CONSTRAINT FK_SIMULACROS_MATRICULA FOREIGN KEY (idMatricula) REFERENCES MATRICULAS(idMatricula) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE USUARIOS_ROLES
    ADD CONSTRAINT FK_USUARIOS_ROLES_ROL FOREIGN KEY (idRol) REFERENCES ROLES(idRol) ON DELETE RESTRICT ON UPDATE RESTRICT,
    ADD CONSTRAINT FK_USUARIOS_ROLES_USUARIO FOREIGN KEY (idUsuario) REFERENCES USUARIOS(idUsuario) ON DELETE RESTRICT ON UPDATE RESTRICT;



INSERT INTO `sedes` (`idSede`, `descripcion`, `direccion`, `telefono`, `estado`, `correo`) VALUES (NULL, 'TRUJILLO - 1', 'Av. Pedro Muñiz', '999999999', '1', 'academiapacifico@gmail.com');
-- Insertar persona
INSERT INTO PERSONAS (nombre, apellido, dni, tipoPersona, correo)
VALUES ('Daniel', 'Agramonte', '87654321', 'TRABAJADOR', 'admin@gmail.com');

-- Insertar usuario (contraseña "admin123" en texto plano o hasheada)
-- Si quieres hasheada usa bcrypt en tu app antes de insertar.
INSERT INTO USUARIOS (password, estado, usuario, idPersona)
VALUES ('$2a$10$V/4mCGyVXo6hHtzX5bTnDOYfJlz0a2lFDP6tjpREo8vW.PGqVNjmK', 1, 'admin@gmail.com', 1);

-- Insertar rol ADMIN
INSERT INTO ROLES (descripcion, estado)
VALUES ('ADMIN', 1);

-- Asignar rol ADMIN al usuario
INSERT INTO USUARIOS_ROLES (idRol, idUsuario)
VALUES (1, 1);
